# Generated by Django 4.0.4 on 2022-05-25 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memomodel',
            name='作成した日付',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
